
from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(700, 500)
        MainWindow.setMinimumSize(QtCore.QSize(700, 500))
        MainWindow.setMaximumSize(QtCore.QSize(700, 500))
        MainWindow.setStyleSheet("QWidget {font-family: 'Verdana'; color: #202020; background: #E6F0F2;}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 30, 701, 51))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: #1A1A1A;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 80, 701, 41))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: #2E2E2E;")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.led_workerid = QtWidgets.QLineEdit(self.centralwidget)
        self.led_workerid.setGeometry(QtCore.QRect(230, 160, 241, 41))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(16)
        self.led_workerid.setFont(font)
        self.led_workerid.setStyleSheet("background-color: #FFFFFF; border: 1px solid #A0A0A0; border-radius: 8px; color: #000000;")
        self.led_workerid.setObjectName("led_workerid")
        self.led_pwd = QtWidgets.QLineEdit(self.centralwidget)
        self.led_pwd.setGeometry(QtCore.QRect(230, 230, 241, 41))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(16)
        self.led_pwd.setFont(font)
        self.led_pwd.setStyleSheet("background-color: #FFFFFF; border: 1px solid #A0A0A0; border-radius: 8px; color: #000000;")
        self.led_pwd.setEchoMode(QtWidgets.QLineEdit.Password)
        self.led_pwd.setObjectName("led_pwd")
        self.btn_login = QtWidgets.QPushButton(self.centralwidget)
        self.btn_login.setGeometry(QtCore.QRect(240, 300, 221, 41))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(14)
        self.btn_login.setFont(font)
        self.btn_login.setStyleSheet("background-color: #008080; border-radius: 15px; color: white;")
        self.btn_login.setObjectName("btn_login")
        self.btn_reg = QtWidgets.QPushButton(self.centralwidget)
        self.btn_reg.setGeometry(QtCore.QRect(240, 370, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        self.btn_reg.setFont(font)
        self.btn_reg.setStyleSheet("QPushButton { color: #0066CC; background-color: transparent; border: none; } QPushButton:hover { text-decoration: underline; }")
        self.btn_reg.setObjectName("btn_reg")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.label_footer = QtWidgets.QLabel(self.centralwidget)
        self.label_footer.setGeometry(QtCore.QRect(0, 480, 700, 30))
        self.label_footer.setText("欢迎使用")
        self.label_footer.setAlignment(QtCore.Qt.AlignCenter)
        self.label_footer.setStyleSheet("color: gray; font-size: 10pt; font-family: Verdana;")

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "登录"))
        self.label.setText(_translate("MainWindow", "人脸口罩佩戴检测系统"))
        self.label_2.setText(_translate("MainWindow", "登录"))
        self.led_workerid.setPlaceholderText(_translate("MainWindow", "请输入用户名"))
        self.led_pwd.setPlaceholderText(_translate("MainWindow", "请输入密码"))
        self.btn_login.setText(_translate("MainWindow", "登录"))
        self.btn_reg.setText(_translate("MainWindow", "还没账号？请去注册"))