# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UiMain.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        button_style = """
        QPushButton {
            background-color: #ffffff;
            color: #1a1a1a;
            border: 2px solid #dee2e6;
            border-radius: 10px;
            font-size: 16px;
            font-weight: bold;
            padding: 10px 20px;
        }
        QPushButton:hover {
            background-color: #f8f9fa;
            border-color: #cbd5e1;
        }
        QPushButton:pressed {
            background-color: #e9ecef;
            border-color: #adb5bd;
        }
        """

        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1400, 950)
        MainWindow.setMinimumSize(QtCore.QSize(1400, 950))
        MainWindow.setMaximumSize(QtCore.QSize(1400, 950))

        MainWindow.setStyleSheet("QWidget {font-family: 'Segoe UI', 'Microsoft YaHei';color: #2C3E50;background: #F8F9FA;}")

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_show = QtWidgets.QLabel(self.centralwidget)
        self.label_show.setGeometry(QtCore.QRect(50, 120, 560, 360))
        self.label_show.setMinimumSize(QtCore.QSize(560, 360))
        self.label_show.setMaximumSize(QtCore.QSize(560, 360))
        MainWindow.setStyleSheet("QWidget {font-family: 'Segoe UI', 'Microsoft YaHei'; color: #1A1A1A; background: #E6ECF0;}")

        self.label_show.setFrameShape(QtWidgets.QFrame.Box)
        self.label_show.setText("")
        self.label_show.setObjectName("label_show")

        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(780, 530, 420, 241))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(-1)
        self.tableWidget.setFont(font)
        self.tableWidget.setStyleSheet("""
        QTableWidget {
            background-color: #f0f4f8;
            alternate-background-color: #e5ecf3;
            gridline-color: #cbd5e1;
            border: 1px solid #cbd5e1;
            border-radius: 10px;
            padding: 4px;
            font-family: "Microsoft YaHei", "Segoe UI";
            font-size: 13px;
        }

        QHeaderView::section {
            background-color: #dbeafe;
            color: #1e293b;
            padding: 8px;
            border: none;
            font-weight: bold;
            font-size: 13px;
            border-radius: 4px;
        }

        QHeaderView::section:hover {
            background-color: #bfdbfe;
        }

        QTableWidget QTableCornerButton::section {
            background-color: #dbeafe;
            border: none;
        }

        QTableWidget::item:selected {
            background-color: #93c5fd;
            color: #0f172a;
        }

        QTableWidget::item:alternate {
            background-color: #e5ecf3;
        }
        """)

        self.tableWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.tableWidget.verticalHeader().setVisible(False)

        self.ModelBtn = QtWidgets.QPushButton(self.centralwidget)
        self.ModelBtn.setGeometry(QtCore.QRect(120, 610, 141, 41))
        self.ModelBtn.setObjectName("ModelBtn")
        self.ModelBtn.setStyleSheet(button_style)  # ✅ 添加

        self.PicBtn = QtWidgets.QPushButton(self.centralwidget)
        self.PicBtn.setGeometry(QtCore.QRect(120, 530, 141, 41))
        self.PicBtn.setObjectName("PicBtn")
        self.PicBtn.setStyleSheet(button_style)  # ✅ 添加

        self.VideoBtn = QtWidgets.QPushButton(self.centralwidget)
        self.VideoBtn.setGeometry(QtCore.QRect(320, 530, 141, 41))
        self.VideoBtn.setObjectName("VideoBtn")
        self.VideoBtn.setStyleSheet(button_style)  # ✅ 添加

        self.CapBtn = QtWidgets.QPushButton(self.centralwidget)
        self.CapBtn.setGeometry(QtCore.QRect(320, 610, 141, 41))
        self.CapBtn.setObjectName("CapBtn")
        self.CapBtn.setStyleSheet(button_style)  # ✅ 添加

        self.SaveBtn = QtWidgets.QPushButton(self.centralwidget)
        self.SaveBtn.setGeometry(QtCore.QRect(520, 530, 141, 41))
        self.SaveBtn.setObjectName("SaveBtn")
        self.SaveBtn.setStyleSheet(button_style)  # ✅ 添加

        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 30, 1171, 51))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")

        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(30)
        font.setBold(True)
        self.label_3.setFont(font)

        self.label_3.setStyleSheet("""
        QLabel {
            font-family: 'Segoe UI', 'Microsoft YaHei';
            font-size: 30px;
            font-weight: bold;
            color: #2C3E50;
            background-color: #f8fafc;
            border-bottom: 2px solid #dee2e6;
            padding: 10px;
        }
        """)

        self.label_show_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_show_2.setGeometry(QtCore.QRect(640, 120, 560, 360))
        self.label_show_2.setMinimumSize(QtCore.QSize(560, 360))
        self.label_show_2.setMaximumSize(QtCore.QSize(560, 360))
        self.label_show_2.setStyleSheet("""
        QLabel {
            background-color: #FFFFFF;
            border-radius: 12px;
            border: 1px solid #CED4DA;
        }
        """)
        self.label_show_2.setFrameShape(QtWidgets.QFrame.Box)
        self.label_show_2.setText("")
        self.label_show_2.setObjectName("label_show_2")

        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(40, 100, 1171, 401))
        self.frame.setStyleSheet("""
        QFrame {
            background-color: #FFFFFF;
            border-radius: 12px;
            border: 1px solid #CED4DA;
        }
        """)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")

        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(80, 690, 125, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(80, 750, 125, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")

        self.conf_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.conf_lineEdit.setGeometry(QtCore.QRect(200, 690, 160, 31))
        self.conf_lineEdit.setStyleSheet("""
        QLineEdit {
            font-family: 'Segoe UI', 'Microsoft YaHei';
            font-size: 18px;
            font-weight: bold;
            color: #1a1a1a;
            background-color: #ffffff;
            border: 1px solid #dee2e6;
            border-radius: 6px;
            padding: 4px 8px;
        }
        """)
        self.conf_lineEdit.setText("0.5")
        self.conf_lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.conf_lineEdit.setObjectName("conf_lineEdit")

        self.iou_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.iou_lineEdit.setGeometry(QtCore.QRect(200, 750, 160, 31))
        self.iou_lineEdit.setStyleSheet("""
                QLineEdit {
                    font-family: 'Segoe UI', 'Microsoft YaHei';
                    font-size: 18px;
                    font-weight: bold;
                    color: #1a1a1a;
                    background-color: #ffffff;
                    border: 1px solid #dee2e6;
                    border-radius: 6px;
                    padding: 4px 8px;
                }
                """)

        self.iou_lineEdit.setText("0.5")
        self.iou_lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.iou_lineEdit.setObjectName("iou_lineEdit")


        self.ExitBtn = QtWidgets.QPushButton(self.centralwidget)
        self.ExitBtn.setGeometry(QtCore.QRect(520, 610, 141, 41))
        self.ExitBtn.setStyleSheet("""
            QPushButton {
                background-color: #ffffff;
                color: #dc3545;  /* Bootstrap红色 */
                border: 2px solid #dc3545;
                border-radius: 10px;
                font-size: 16px;
                font-weight: bold;
                padding: 10px 20px;
            }
            QPushButton:hover {
                background-color: #ffe5e8;
                border-color: #c82333;
            }
            QPushButton:pressed {
                background-color: #f8d7da;
                border-color: #bd2130;
            }
        """)
        self.ExitBtn.setObjectName("ExitBtn")

        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(482, 690, 125, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(18)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.time_lb = QtWidgets.QLabel(self.centralwidget)
        self.time_lb.setGeometry(QtCore.QRect(555, 690, 91, 31))
        self.time_lb.setStyleSheet("""
        QLabel {
            font-family: 'Segoe UI', 'Microsoft YaHei';
            font-size: 18px;
            font-weight: bold;
            color: #2C3E50;
            background-color: #ffffff;
            border: 1px solid #dee2e6;
            border-radius: 6px;
            padding: 2px 6px;
        }
        """)

        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.time_lb.setFont(font)
        self.time_lb.setText("")
        self.time_lb.setObjectName("time_lb")
        '''self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(482, 750, 125, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_nums = QtWidgets.QLabel(self.centralwidget)
        self.label_nums.setGeometry(QtCore.QRect(555, 750, 91, 31))
        self.label_nums.setStyleSheet("""
        QLabel {
            font-family: 'Segoe UI', 'Microsoft YaHei';
            font-size: 18px;
            font-weight: bold;
            color: #2C3E50;
            background-color: #ffffff;
            border: 1px solid #dee2e6;
            border-radius: 6px;
            padding: 2px 6px;
        }
        """)

        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_nums.setFont(font)
        self.label_nums.setText("")
        self.label_nums.setObjectName("label_nums")'''
        self.frame.raise_()
        self.label_show.raise_()
        self.tableWidget.raise_()
        self.ModelBtn.raise_()
        self.PicBtn.raise_()
        self.VideoBtn.raise_()
        self.CapBtn.raise_()
        self.SaveBtn.raise_()
        self.label_3.raise_()
        self.label_show_2.raise_()
        self.label_11.raise_()
        self.label_12.raise_()



        self.ExitBtn.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "YOLOv5人脸口罩佩戴检测系统"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Class"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Confidence"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Position"))
        self.ModelBtn.setText(_translate("MainWindow", "选择模型"))
        self.PicBtn.setText(_translate("MainWindow", "选择图片"))
        self.VideoBtn.setText(_translate("MainWindow", "选择视频"))
        self.CapBtn.setText(_translate("MainWindow", "选择摄像头"))
        self.SaveBtn.setText(_translate("MainWindow", "开始保存"))

        self.ExitBtn.setText(_translate("MainWindow", "退出"))

        self.label_3.setText(_translate("MainWindow", "人脸口罩佩戴检测系统"))

        self.label_11.setText(_translate("MainWindow",
                                         "<span style='font-size:16px; font-family:\"Segoe UI\",\"Microsoft YaHei\"; font-weight:bold; color:#1F2937;'>请输入Conf 阈值：</span>"))
        self.label_12.setText(_translate("MainWindow",
                                         "<span style='font-size:16px; font-family:\"Segoe UI\",\"Microsoft YaHei\"; font-weight:bold; color:#1F2937;'>请输入IOU 阈值：</span>"))


        self.label_10.setText(_translate("MainWindow",
                                         "<span style='font-size:16px; font-family:\"Segoe UI\",\"Microsoft YaHei\"; font-weight:bold; color:#1F2937;'>检测时间：</span>"))
        #self.label.setText(_translate("MainWindow",
                                      #"<span style='font-size:16px; font-family:\"Segoe UI\",\"Microsoft YaHei\"; font-weight:bold; color:#1F2937;'>检测数目：</span>"))

